import test from 'node:test'
import assert from 'node:assert/strict'
import { publicationDecision } from './publish-release.mjs'
const fixture = () => ({ tag: 'v1.2.3', expectedName: 'example-plugin', expectedRepository: 'Example/plugin', actualRepository: 'Example/plugin', source: { name: 'example-plugin', version: '1.2.3', repository: { url: 'git+https://github.com/Example/plugin.git' } }, archive: { name: 'example-plugin', version: '1.2.3', repository: { url: 'git+https://github.com/Example/plugin.git' } }, integrity: 'sha512-archive', sha256: 'archive', assetDigest: 'sha256:archive', tagCommit: 'source-commit', workflowCommit: 'source-commit' })
test('a new release requires the same tag, package, archive and source commit', () => assert.deepEqual(publicationDecision(fixture()), { publish: true, version: '1.2.3', npmTag: 'latest' }))
test('a matching immutable npm version is skipped rather than republished', () => { const x=fixture(); x.registryVersion={ name:'example-plugin',version:'1.2.3',dist:{integrity:x.integrity} }; assert.equal(publicationDecision(x).publish,false) })
test('an existing npm version with different bytes is rejected', () => { const x=fixture(); x.registryVersion={name:'example-plugin',version:'1.2.3',dist:{integrity:'sha512-other'}}; assert.throws(()=>publicationDecision(x),/different contents/) })
test('a changed release asset is rejected before publishing', () => assert.throws(()=>publicationDecision({...fixture(),assetDigest:'sha256-other'}),/asset digest/))
test('a wrong repository or package cannot be published', () => { assert.throws(()=>publicationDecision({...fixture(),actualRepository:'Other/plugin'}),/repository/); const x=fixture(); x.archive.name='other-plugin'; assert.throws(()=>publicationDecision(x),/same package/) })
test('source and archive version mismatches are rejected', () => { const x=fixture(); x.source.version='1.2.2'; assert.throws(()=>publicationDecision(x),/same package/); assert.throws(()=>publicationDecision({...fixture(),tag:'v1.2.4'}),/same package/) })
test('a new release needs canonical repository metadata and the actual source commit', () => { const x=fixture(); x.archive.repository.url='git+https://github.com/Old/plugin.git'; assert.throws(()=>publicationDecision(x),/canonical/); assert.throws(()=>publicationDecision({...fixture(),workflowCommit:'other-commit'}),/tag ref/) })
test('untrusted tag text is refused and prereleases use next, not latest', () => { for(const tag of ['main','v1.2','v1.2.3; echo no']) assert.throws(()=>publicationDecision({...fixture(),tag}),/exact/); const x=fixture(); x.tag='v1.2.3-beta.1'; x.source.version=x.archive.version='1.2.3-beta.1'; assert.equal(publicationDecision(x).npmTag,'next') })
